### ISSUE TITLE
Don't work with fresh Ubuntu 18.04

### ISSUE THREAD

**Issue by d4rkf4b** [bobwya/build-multilib-wine#6]
With fresh install, after `generate-conf`, 
![screenshot from 2018-07-01 11-30-12](https://user-images.githubusercontent.com/40733077/42132979-69ad62ca-7d22-11e8-9830-c0abc04f9634.png)

This with `help` or any other command

With my old install upgraded from 17.10, script work fine

**Comment by bobwya** [comment]
Yup this looks legit. Probably introduced by the Q/A "fixes" I pushed last month. I won't be able to push a fix till after Wednesday 2nd July...

**Comment by bobwya** [comment]
Please reopen this issue, if you find the re-factored configuration file parser still isn't working for you!

**Comment by d4rkf4b** [comment]
![screenshot from 2018-07-06 21-06-32](https://user-images.githubusercontent.com/40733077/42396164-ecd0f878-8160-11e8-84e6-308da655a898.png)

Don't know how to reopen

**Comment by bobwya** [comment]
What's the output from (change the configuration file path, if appropriate):

```
hexdump -C /etc/build_multilib_wine.conf
```

Please don't post this output as a screenshot, just post it inline as text, ideally with **code** tags (wrap the text with triple back-tics, on their own line).

Also what's the output from:

```
awk --version 2>/dev/null || awk -W version 2>/dev/null

'ls' -hl /usr/bin/awk
```

(again as text, **code** tags, please)

**Comment by d4rkf4b** [comment]
`hexdump -C /etc/build_multilib_wine.conf`

00000000  23 0a 23 20 2f 65 74 63  2f 62 75 69 6c 64 5f 6d  |#.# /etc/build_m|
00000010  75 6c 74 69 6c 69 62 5f  77 69 6e 65 2e 63 6f 6e  |ultilib_wine.con|
00000020  66 20 2d 20 43 6f 6e 66  69 67 75 72 61 74 69 6f  |f - Configuratio|
00000030  6e 20 66 69 6c 65 20 66  6f 72 20 62 75 69 6c 64  |n file for build|
00000040  5f 6d 75 6c 74 69 6c 69  62 5f 77 69 6e 65 2e 73  |_multilib_wine.s|
00000050  68 0a 23 0a 23 20 47 65  6e 65 72 61 74 65 64 20  |h.#.# Generated |
00000060  62 79 20 62 75 69 6c 64  5f 6d 75 6c 74 69 6c 69  |by build_multili|
00000070  62 5f 77 69 6e 65 2e 73  68 20 28 67 69 74 2d 29  |b_wine.sh (git-)|
00000080  20 6f 6e 20 46 72 69 20  4a 75 6c 20 20 36 20 32  | on Fri Jul  6 2|
00000090  31 3a 30 35 3a 31 39 20  43 45 53 54 20 32 30 31  |1:05:19 CEST 201|
000000a0  38 20 28 62 75 69 6c 64  20 76 65 72 73 69 6f 6e  |8 (build version|
000000b0  3a 20 67 69 74 2d 29 0a  23 0a 23 20 55 6e 63 6f  |: git-).#.# Unco|
000000c0  6d 6d 65 6e 74 20 74 68  65 20 64 65 66 61 75 6c  |mment the defaul|
000000d0  74 2c 20 65 78 61 6d 70  6c 65 20 6f 70 74 69 6f  |t, example optio|
000000e0  6e 73 20 61 6e 64 20 63  68 61 6e 67 65 20 74 68  |ns and change th|
000000f0  65 73 65 20 61 73 20 64  65 73 69 72 65 64 2e 0a  |ese as desired..|
00000100  23 0a 23 20 47 6c 6f 62  61 6c 0a 23 0a 23 20 43  |#.# Global.#.# C|
00000110  4f 4c 4f 55 52 3d 30 20  23 20 64 65 66 61 75 6c  |OLOUR=0 # defaul|
00000120  74 0a 23 0a 23 20 44 69  72 65 63 74 6f 72 69 65  |t.#.# Directorie|
00000130  73 0a 23 0a 23 20 49 6e  73 74 61 6c 6c 61 74 69  |s.#.# Installati|
00000140  6f 6e 20 70 72 65 66 69  78 20 64 69 72 65 63 74  |on prefix direct|
00000150  6f 72 79 20 69 6e 20 77  68 69 63 68 20 57 69 6e  |ory in which Win|
00000160  65 20 6c 69 62 72 61 72  69 65 73 2c 20 62 69 6e  |e libraries, bin|
00000170  61 72 69 65 73 2c 20 65  74 63 2e 20 61 72 65 20  |aries, etc. are |
00000180  69 6e 73 74 61 6c 6c 65  64 2e 0a 23 20 50 52 45  |installed..# PRE|
00000190  46 49 58 3d 22 2f 68 6f  6d 65 2f 66 61 62 2f 75  |FIX="/home/fab/u|
000001a0  73 72 22 20 23 20 64 65  66 61 75 6c 74 0a 23 0a  |sr" # default.#.|
000001b0  23 20 52 6f 6f 74 20 64  69 72 65 63 74 6f 72 79  |# Root directory|
000001c0  20 77 68 65 72 65 20 73  6f 75 72 63 65 73 20 61  | where sources a|
000001d0  72 65 20 73 74 6f 72 65  64 20 69 2e 65 2e 20 63  |re stored i.e. c|
000001e0  6c 6f 6e 65 73 20 6f 66  20 57 69 6e 65 20 28 61  |lones of Wine (a|
000001f0  6e 64 20 57 69 6e 65 2d  53 74 61 67 69 6e 67 29  |nd Wine-Staging)|
00000200  20 47 69 74 20 74 72 65  65 73 2e 0a 23 20 53 4f  | Git trees..# SO|
00000210  55 52 43 45 5f 52 4f 4f  54 3d 22 2f 68 6f 6d 65  |URCE_ROOT="/home|
00000220  2f 66 61 62 2f 57 69 6e  65 2f 53 6f 75 72 63 65  |/fab/Wine/Source|
00000230  22 20 23 20 64 65 66 61  75 6c 74 0a 23 0a 23 20  |" # default.#.# |
00000240  52 6f 6f 74 20 64 69 72  65 63 74 6f 72 79 20 77  |Root directory w|
00000250  68 65 72 65 20 74 68 65  20 62 69 6e 61 72 79 20  |here the binary |
00000260  62 75 69 6c 64 73 20 61  72 65 20 73 74 6f 72 65  |builds are store|
00000270  64 20 2d 20 22 6f 75 74  2d 6f 66 2d 74 72 65 65  |d - "out-of-tree|
00000280  22 20 62 75 69 6c 64 2e  0a 23 20 42 55 49 4c 44  |" build..# BUILD|
00000290  5f 52 4f 4f 54 3d 22 2f  68 6f 6d 65 2f 66 61 62  |_ROOT="/home/fab|
000002a0  2f 57 69 6e 65 2f 42 75  69 6c 64 22 20 23 20 64  |/Wine/Build" # d|
000002b0  65 66 61 75 6c 74 0a 23  0a 23 20 50 61 74 63 68  |efault.#.# Patch|
000002c0  20 66 69 6c 65 73 20 28  69 6e 20 2d 70 31 20 64  | files (in -p1 d|
000002d0  69 66 66 20 66 6f 72 6d  61 74 29 2c 20 69 6e 20  |iff format), in |
000002e0  74 68 65 73 65 20 64 69  72 65 63 74 6f 72 69 65  |these directorie|
000002f0  73 2c 20 61 72 65 20 61  70 70 6c 69 65 64 20 74  |s, are applied t|
00000300  6f 20 74 68 65 20 57 69  6e 65 20 73 6f 75 72 63  |o the Wine sourc|
00000310  65 2e 0a 23 20 55 53 45  52 5f 50 41 54 43 48 5f  |e..# USER_PATCH_|
00000320  44 49 52 45 43 54 4f 52  49 45 53 3d 28 20 22 64  |DIRECTORIES=( "d|
00000330  69 72 31 22 20 22 64 69  72 32 22 20 29 0a 23 20  |ir1" "dir2" ).# |
00000340  55 53 45 52 5f 50 41 54  43 48 5f 44 49 52 45 43  |USER_PATCH_DIREC|
00000350  54 4f 52 49 45 53 2b 3d  28 20 22 64 69 72 33 22  |TORIES+=( "dir3"|
00000360  20 22 64 69 72 34 22 20  29 0a 23 0a 23 0a 23 20  | "dir4" ).#.#.# |
00000370  56 65 72 73 69 6f 6e 69  6e 67 0a 23 0a 23 20 45  |Versioning.#.# E|
00000380  6e 61 62 6c 65 20 2f 20  64 69 73 61 62 6c 65 20  |nable / disable |
00000390  57 69 6e 65 2d 53 74 61  67 69 6e 67 20 70 61 74  |Wine-Staging pat|
000003a0  63 68 73 65 74 20 73 75  70 70 6f 72 74 2e 0a 23  |chset support..#|
000003b0  20 57 49 4e 45 5f 53 54  41 47 49 4e 47 3d 66 61  | WINE_STAGING=fa|
000003c0  6c 73 65 20 23 20 64 65  66 61 75 6c 74 0a 23 0a  |lse # default.#.|
000003d0  23 20 57 69 6e 65 20 2f  20 57 69 6e 65 2d 53 74  |# Wine / Wine-St|
000003e0  61 67 69 6e 67 20 76 65  72 73 69 6f 6e 20 74 6f  |aging version to|
000003f0  20 62 75 69 6c 64 2e 0a  23 20 57 49 4e 45 5f 56  | build..# WINE_V|
00000400  45 52 53 49 4f 4e 3d 22  31 2e 39 2e 32 30 22 0a  |ERSION="1.9.20".|
00000410  23 0a 23 20 47 69 74 20  62 72 61 6e 63 68 20 6f  |#.# Git branch o|
00000420  66 20 57 69 6e 65 20 74  6f 20 62 75 69 6c 64 20  |f Wine to build |
00000430  28 57 49 4e 45 5f 53 54  41 47 49 4e 47 3d 6e 6f  |(WINE_STAGING=no|
00000440  29 2e 0a 23 20 57 49 4e  45 5f 42 52 41 4e 43 48  |)..# WINE_BRANCH|
00000450  3d 22 6d 61 73 74 65 72  22 0a 23 0a 23 20 47 69  |="master".#.# Gi|
00000460  74 20 63 6f 6d 6d 69 74  20 28 53 48 41 2d 31 20  |t commit (SHA-1 |
00000470  68 61 73 68 29 20 6f 66  20 57 69 6e 65 20 74 6f  |hash) of Wine to|
00000480  20 62 75 69 6c 64 20 28  57 49 4e 45 5f 53 54 41  | build (WINE_STA|
00000490  47 49 4e 47 3d 6e 6f 29  2e 0a 23 20 57 49 4e 45  |GING=no)..# WINE|
000004a0  5f 43 4f 4d 4d 49 54 3d  22 22 0a 23 0a 23 20 47  |_COMMIT="".#.# G|
000004b0  69 74 20 62 72 61 6e 63  68 20 6f 66 20 57 69 6e  |it branch of Win|
000004c0  65 2d 53 74 61 67 69 6e  67 20 74 6f 20 62 75 69  |e-Staging to bui|
000004d0  6c 64 20 28 57 49 4e 45  5f 53 54 41 47 49 4e 47  |ld (WINE_STAGING|
000004e0  3d 79 65 73 29 2e 0a 23  20 57 49 4e 45 5f 53 54  |=yes)..# WINE_ST|
000004f0  41 47 49 4e 47 5f 42 52  41 4e 43 48 3d 22 6d 61  |AGING_BRANCH="ma|
00000500  73 74 65 72 22 0a 23 0a  23 20 47 69 74 20 63 6f  |ster".#.# Git co|
00000510  6d 6d 69 74 20 28 53 48  41 2d 31 20 68 61 73 68  |mmit (SHA-1 hash|
00000520  29 20 6f 66 20 57 69 6e  65 2d 53 74 61 67 69 6e  |) of Wine-Stagin|
00000530  67 20 74 6f 20 62 75 69  6c 64 20 28 57 49 4e 45  |g to build (WINE|
00000540  5f 53 54 41 47 49 4e 47  3d 79 65 73 29 2e 0a 23  |_STAGING=yes)..#|
00000550  20 57 49 4e 45 5f 53 54  41 47 49 4e 47 5f 43 4f  | WINE_STAGING_CO|
00000560  4d 4d 49 54 3d 22 22 0a  23 0a 23 0a 23 20 4c 6f  |MMIT="".#.#.# Lo|
00000570  67 67 69 6e 67 0a 23 0a  23 20 45 6e 61 62 6c 65  |gging.#.# Enable|
00000580  20 2f 20 64 69 73 61 62  6c 65 20 6f 70 65 72 61  | / disable opera|
00000590  74 69 6f 6e 20 6c 6f 67  67 69 6e 67 20 66 6f 72  |tion logging for|
000005a0  20 63 6f 6d 6d 61 6e 64  73 3a 20 73 65 74 75 70  | commands: setup|
000005b0  2d 63 68 72 6f 6f 74 3b  20 75 70 67 72 61 64 65  |-chroot; upgrade|
000005c0  2d 63 68 72 6f 6f 74 3b  20 62 75 69 6c 64 2d 61  |-chroot; build-a|
000005d0  6c 6c 20 28 61 6e 64 20  73 75 62 2d 70 68 61 73  |ll (and sub-phas|
000005e0  65 73 29 2e 0a 23 20 4c  4f 47 47 49 4e 47 3d 31  |es)..# LOGGING=1|
000005f0  20 23 20 64 65 66 61 75  6c 74 0a 23 0a 23 20 44  | # default.#.# D|
00000600  69 72 65 63 74 6f 72 79  20 74 6f 20 68 6f 6c 64  |irectory to hold|
00000610  20 6c 6f 67 20 66 69 6c  65 73 20 2d 20 72 65 63  | log files - rec|
00000620  6f 72 64 69 6e 67 20 61  6c 6c 20 74 68 65 20 73  |ording all the s|
00000630  63 72 69 70 74 20 6f 70  65 72 61 74 69 6f 6e 73  |cript operations|
00000640  2e 0a 23 20 4c 4f 47 5f  44 49 52 45 43 54 4f 52  |..# LOG_DIRECTOR|
00000650  59 3d 22 2f 68 6f 6d 65  2f 66 61 62 2f 57 69 6e  |Y="/home/fab/Win|
00000660  65 2f 42 75 69 6c 64 2f  4c 6f 67 73 22 20 23 20  |e/Build/Logs" # |
00000670  64 65 66 61 75 6c 74 0a  23 0a 23 20 43 6f 6d 70  |default.#.# Comp|
00000680  72 65 73 73 69 6f 6e 20  74 6f 20 62 65 20 61 70  |ression to be ap|
00000690  70 6c 69 65 64 20 74 6f  20 6e 65 77 20 6c 6f 67  |plied to new log|
000006a0  20 66 69 6c 65 73 2e 0a  23 20 4c 4f 47 5f 43 4f  | files..# LOG_CO|
000006b0  4d 50 52 45 53 53 49 4f  4e 3d 22 67 7a 69 70 22  |MPRESSION="gzip"|
000006c0  20 23 20 64 65 66 61 75  6c 74 0a 23 0a 23 0a 23  | # default.#.#.#|
000006d0  20 42 75 69 6c 64 69 6e  67 0a 23 0a 23 20 4e 75  | Building.#.# Nu|
000006e0  6d 62 65 72 20 6f 66 20  70 72 6f 63 65 73 73 6f  |mber of processo|
000006f0  72 20 74 68 72 65 61 64  73 20 74 6f 20 75 73 65  |r threads to use|
00000700  2e 0a 23 20 54 48 52 45  41 44 53 3d 22 33 22 20  |..# THREADS="3" |
00000710  23 20 64 65 66 61 75 6c  74 0a 23 0a 23 20 57 69  |# default.#.# Wi|
00000720  6e 65 2d 53 74 61 67 69  6e 67 20 73 75 62 70 61  |ne-Staging subpa|
00000730  74 63 68 73 65 74 73 20  74 6f 20 6f 70 74 69 6f  |tchsets to optio|
00000740  6e 61 6c 6c 79 20 64 69  73 61 62 6c 65 2e 09 09  |nally disable...|
00000750  5b 73 72 63 2d 70 72 65  70 61 72 65 5d 0a 23 20  |[src-prepare].# |
00000760  57 49 4e 45 5f 53 54 41  47 49 4e 47 5f 45 58 43  |WINE_STAGING_EXC|
00000770  4c 55 44 45 3d 22 22 20  23 20 64 65 66 61 75 6c  |LUDE="" # defaul|
00000780  74 0a 23 0a 23 20 43 6f  6e 66 69 67 75 72 61 74  |t.#.# Configurat|
00000790  69 6f 6e 20 6f 70 74 69  6f 6e 73 20 66 6f 72 20  |ion options for |
000007a0  77 69 6e 65 2e 09 09 09  09 09 09 20 5b 73 72 63  |wine....... [src|
000007b0  2d 63 6f 6e 66 69 67 75  72 65 5d 0a 23 20 57 49  |-configure].# WI|
000007c0  4e 45 5f 43 4f 4e 46 49  47 55 52 41 54 49 4f 4e  |NE_CONFIGURATION|
000007d0  3d 22 2d 2d 77 69 74 68  6f 75 74 2d 68 61 6c 20  |="--without-hal |
000007e0  2d 2d 77 69 74 68 6f 75  74 2d 76 34 6c 20 2d 2d  |--without-v4l --|
000007f0  77 69 74 68 6f 75 74 2d  6f 73 73 22 20 23 20 64  |without-oss" # d|
00000800  65 66 61 75 6c 74 0a 23  0a 23 20 43 46 4c 41 47  |efault.#.# CFLAG|
00000810  53 20 28 63 6f 6d 70 69  6c 65 20 66 6c 61 67 73  |S (compile flags|
00000820  29 20 74 6f 20 70 61 73  73 20 74 6f 20 77 69 6e  |) to pass to win|
00000830  65 2e 09 09 09 09 20 5b  73 72 63 2d 63 6f 6e 66  |e..... [src-conf|
00000840  69 67 75 72 65 5d 0a 23  20 57 49 4e 45 5f 43 46  |igure].# WINE_CF|
00000850  4c 41 47 53 3d 22 2d 6d  61 72 63 68 3d 6e 61 74  |LAGS="-march=nat|
00000860  69 76 65 20 2d 6d 74 75  6e 65 3d 6e 61 74 69 76  |ive -mtune=nativ|
00000870  65 22 20 23 20 64 65 66  61 75 6c 74 0a 23 0a 23  |e" # default.#.#|
00000880  20 4d 61 6b 65 20 6f 70  74 69 6f 6e 73 20 74 6f  | Make options to|
00000890  20 75 73 65 20 77 68 65  6e 20 63 6f 6d 70 69 6c  | use when compil|
000008a0  69 6e 67 20 77 69 6e 65  2e 09 09 09 09 5b 73 72  |ing wine.....[sr|
000008b0  63 2d 63 6f 6d 70 69 6c  65 5d 0a 23 20 57 49 4e  |c-compile].# WIN|
000008c0  45 5f 4d 41 4b 45 5f 4f  50 54 49 4f 4e 53 3d 22  |E_MAKE_OPTIONS="|
000008d0  2d 6a 33 22 20 23 20 64  65 66 61 75 6c 74 0a 23  |-j3" # default.#|
000008e0  0a 23 0a 23 20 4f 53 20  56 65 72 73 69 6f 6e 20  |.#.# OS Version |
000008f0  4f 76 65 72 72 69 64 65  20 28 65 2e 67 2e 20 63  |Override (e.g. c|
00000900  72 6f 73 73 2d 62 75 69  6c 64 69 6e 67 20 66 6f  |ross-building fo|
00000910  72 20 61 6e 6f 74 68 65  72 20 44 65 62 69 61 6e  |r another Debian|
00000920  20 2f 20 55 62 75 6e 74  75 20 76 65 72 73 69 6f  | / Ubuntu versio|
00000930  6e 29 0a 23 20 4c 53 42  5f 43 4f 44 45 4e 41 4d  |n).# LSB_CODENAM|
00000940  45 3d 22 22 20 23 20 64  65 66 61 75 6c 74 3a 20  |E="" # default: |
00000950  6c 73 62 5f 72 65 6c 65  61 73 65 20 2d 73 63 0a  |lsb_release -sc.|
00000960

**Comment by d4rkf4b** [comment]
`awk --version 2>/dev/null || awk -W version 2>/dev/null`
`mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan`

`'ls' -hl /usr/bin/awk`
`lrwxrwxrwx 1 root root 21 Jun 28 16:11 /usr/bin/awk -> /etc/alternatives/awk`

**Comment by d4rkf4b** [comment]
If I install gawk script works.
Using it in my old install but not the default alternative into Ubuntu 18.04. Seem to be mawk

Problem solved

**Comment by bobwya** [comment]
@d4rkf4b 

I can't support such an ancient version of **mawk**. The build script is written to be compatible with a modern version of **mawk** (or other Posix-compliant **awk** variant)...
I.e. [Thomas E Dickey's fork](https://invisible-island.net/mawk/CHANGES.html).
Not a version from over a decade ago!

Yet another unfathomable decision by the Debian maintainers...
