### ISSUE TITLE
Compiling error of Wine (everything else succeded)

### ISSUE THREAD

**Issue by d762** [bobwya/build-multilib-wine#9]
I posted it on askubuntu. It has a much nicer formating so check it out there!

https://askubuntu.com/questions/1218737/compiling-multilib-wine-gone-wrong

**Comment by d762** [comment]
this is where it breaks down:

`gcc -m64 -c -o scroll.o /home/icbosk/Programs/Wine/Source/wine/dlls/user32/scroll.c -I. \
  -I/home/icbosk/Programs/Wine/Source/wine/dlls/user32 -I../../include \
  -I/home/icbosk/Programs/Wine/Source/wine/include -I/usr/include/libpng16 -D__WINESRC__ -D_USER32_ \
  -D_WINABLE_ -D_REENTRANT -fPIC -Wall -pipe -fno-stack-protector -fno-strict-aliasing \
  -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers -Wshift-overflow=2 \
  -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith \
  -Wlogical-op -march=native -mtune=native
/home/icbosk/Programs/Wine/Source/wine/dlls/user32/tests/sysparams.c: In function ‘test_EnumDisplaySettings’:
/home/icbosk/Programs/Wine/Source/wine/dlls/user32/tests/sysparams.c:3146:41: error: initializer element is not constant
     static const DWORD setting_fields = mode_fields | DM_POSITION;`

**Comment by bobwya** [comment]
@d762 

That's not really enough information to go on.

- What Wine (or Wine Staging) Git commit did you compile against?
- What (if any) user patches did you apply?

Also you should just attach the **full Wine build log** using the button at the bottom of the Github edit box...

![Github](https://user-images.githubusercontent.com/2497436/77593093-7ce56600-6eeb-11ea-8ef0-a6033efe7e16.jpg)

Please don't link to external sites, unless it's really necessary...

Thanks
Bob

**Comment by bobwya** [comment]
Closing issue, as requested log has not been supplied...
